version: 2
updates:
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
    commit-message:
      prefix: "[Dependabot]"
    labels: [dependencies]

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[Dependabot]"
    labels: [dependencies]

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[Dependabot]"
    labels: [dependencies]

    # Allow security updates, but do not automatically raise its version for routine version updates.
    ignore:
      - dependency-name: "org.keycloak:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[Dependabot]"
    labels: [dependencies]
